---
title: "The Project"
author: "Ian Curtis, Stacy Keydel, Sarba Uprety"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

```{r read_data, message=FALSE}
my_files <- list.files(path=here::here("data/"), pattern="*.csv", full.names = TRUE)
big_spotify <- read_csv(my_files)
```
```{r}
spotify_release_year <- spotify %>%
 mutate(release_year = format(release_date, format = "%Y"))
  
```

```{r adjust_vars}
spotify$release_date <- ymd(spotify$release_date)
# Some of these are NA because they are coded in as just years. We can just use the year column and if we need months we will have to add a note.

# need to create year column

```


```{r eda_numeric}
funs <- c(mean = mean, median = median, max = max, min = min)
spotify %>% 
  select(where(is.numeric)) %>% 
  map_df(~ funs %>%
           map(exec, .x), .id = "var")
# Go back to look at loudness, tempo, duration_ms, time_signature, year
```

```{r}
spotify <- spotify %>% 
  mutate(duration_s = as.duration(duration_ms) / 1000)
```

```{r eda_loudness}
spotify %>% 
  filter(loudness > 5) %>% 
  select(name, artists, loudness) %>% 
  arrange(desc(loudness))
# Some songs are silent
# Some songs are so ridiculously loud (like TV static)
```

```{r eda_tempo}
spotify %>% 
  filter(tempo > 200) %>% 
  select(name, artists, tempo) %>% 
  arrange(desc(tempo))
#spotify %>%  ggplot(aes(x = tempo)) +
  #geom_bar()
# 0 tempo: some are short or have a mess of sound. Some do have a tempo and this may be an error.
# Large tempo: song was recorded in half time and Spotify records it in 4/4
```

```{r eda_duration}
spotify %>% 
  filter(duration_s < 2) %>% 
  select(name, artists, duration_s) %>% 
  arrange(desc(duration_s))
# Human by Anggun is not this slow
```

```{r eda_timesig}
spotify %>% 
  filter(time_signature < 1) %>% 
  select(name, artists, time_signature) %>% 
  arrange(desc(time_signature))
```

```{r}
spotify %>% 
  filter(year < 1500) %>% 
  select(name, artists, year) %>% 
  arrange(desc(year))
# There are ten songs without years. They actually have years so we have to manually add them.
# We also corrected the duration of the incorrect song.
spotify <- spotify %>% 
  mutate(
    year = case_when(
      (name %in% c("Jimmy Neutron", "My Heart")) & (artists == "iCizzle") ~ 2017,
      (name %in% c("I Luv You", "I Am (Invincible)", "Flower Power", "Heard It Low", "Hangin On", "God Loves You", "You In My Life", "I Wonder")) & (artists == "iCizzle") ~ 2018,
      TRUE ~ year
    ),
    duration_s = case_when(
      (name %in% c("Human")) & (artists == "Anggun") ~ duration(198),
      TRUE ~ duration_s
    )
  )
```

```{r}
##EDA
install.packages("funModeling")
install.packages("Hmisc")
library(funModeling) 
library(Hmisc)

#EDA of the data as a whole
glimpse(spotify)
status(spotify)
freq(spotify)
plot_num(spotify)
describe(spotify)

##histogram and count for reference
ggplot (data = spotify) +
  geom_histogram (mapping = aes(x = loudness), binwidth = 0.1)

spotify %>%
  count(loudness)

ggplot(data = spotify, mapping = aes(x = loudness, colour = explicit)) +
  geom_freqpoly(binwidth = 0.1)

#boxplots of variables to look for trends
ggplot(data = spotify, mapping = aes(x = energy)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = popularity)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = danceability)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = key)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = loudness)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = speechiness)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = acousticness)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = liveness)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = valence)) +
  geom_boxplot()
ggplot(data = spotify, mapping = aes(x = tempo)) +
  geom_boxplot()


```

```{r}
##EDA special characters, track_name
spotify %>% 
  select(track_name)

##page 21, 70 with special characters. Only two track names, seems wrong?

 
```

```{r}
spotify_release_year %>%
  filter (artist_name == "Miley Cyrus") %>%
  ggplot() +
  geom_histogram(mapping = aes(x = release_year))
```




